---
version: '3'
tasks:
  cmake:configure:
    internal: true
    cmds:
    - cmake --preset={{.CMAKE_PRESET}}
  cmake:build:
    internal: true
    cmd: cmake --build . --target {{.CMAKE_TARGET}}
  configure:*:
    vars:
      PRESET: "{{index .MATCH 0 }}"
    cmds:
    - task: cmake:configure
      vars:
        CMAKE_PRESET: "{{.PRESET}}"
  build:*:
    vars:
      TARGET: "{{index .MATCH 0 }}"
    cmds:
    - task: cmake:build
      vars:
        CMAKE_TARGET: "{{.TARGET}}"
  default:
    cmds:
    - task: cmake:build
      vars:
        CMAKE_TARGET: "gel"
