---
version: '3'
vars:
  arch:
    sh: uname -m
  triplet: "{{.arch | lower }}-{{if eq OS \"darwin\"}}osx{{else}}{{.OS | lower}}{{end}}"
includes:
  cmake:
    taskfile: "./cmake/"
    internal: true
    dir: "{{.ROOT_DIR}}"
  clean:
    taskfile: ./.tasks/clean.taskfile.yml
tasks:
  debug:configure:
    cmds:
    - task: cmake:configure
      vars:
        preset: debug-{{.triplet}}
  release:configure:
    cmds:
    - task: cmake:configure
      vars:
        preset: release-{{.triplet}}
  build:*:
    vars:
      target: "{{ index .MATCH 0 }}"
    silent: true
    cmds:
    - echo "building {{.target}} target...."
    - task: cmake:build-target
      vars:
        target: "{{ .target }}"
    - echo "%{$fg[yellow]%}%{$reset_color%} {{.target}} finished."
