(ns math
  (defnative acos [a])
  (defnative asin [a])
  (defnative atan [a])
  (defnative ceil [a])
  (defnative cos [a])
  (defnative cosh [a])
  (defnative floor [a])
  (defnative log [a])
  (defnative log10 [a])
  (defnative pow [a b])
  ; (def PI 3.141592654)
  (defnative round [a])
  (defnative sin [a])
  (defnative sinh [a])
  (defnative sqrt [a])
  (defnative tan [a])
  (defnative tanh [a])
  (defnative to-radians [a])
  (defnative to-degrees [a]))