(print (#String? 10))
(print (#String? '()))
(print (#String? 'Hello))
(print (#String? "Hello World"))
(print (#Long? 10))
(print (#Number? 10))
(print (#Fn? print))
(print (#Fn? (fn (x) (print x))))
