function(add_gel_binding target_name target_sources)
  set(binding_name "gel-binding-${target_name}")
  add_library(${binding_name} SHARED ${target_sources})
  target_link_libraries(${binding_name} PUBLIC gelle)
  if(CMAKE_BUILD_TYPE MATCHES "^[rR]elease")
    target_enable_iwyu(${binding_name})
  endif()
endfunction()

add_subdirectory(env/)
add_subdirectory(fs/)
add_subdirectory(math/)
add_subdirectory(os/)
add_subdirectory(process/)
add_subdirectory(rx/)
add_subdirectory(test/)
